import test from 'node:test'
import assert from 'node:assert/strict'
import fs from 'node:fs'
import { hardwareFrequency, hardwareMonth, hardwareEvidenceUrl } from '../docs/.vitepress/theme/lib/hardware-frequency.mjs'

const device = (id, name = id, level = 'model_specified') => ({ hardware_id: id, name, category: 'robot_platform', identity_level: level })
const usage = (id, extra = {}) => ({ hardware_id: id, category: 'robot_platform', review_status: 'verified', source_url: 'https://arxiv.org/html/2609.00001v1', source_locator: '§4', role: 'real_robot', setting: 'real', statement: 'Used this platform in the experiment.', usage_scope: 'study', ...extra })
const work = (id, usages, extra = {}) => ({ work_id: id, title: id, relevance_status: 'included', first_public_date: '2026-09-01', first_public_date_precision: 'day', hardware_usage: usages, ...extra })

test('frequency counts canonical works once, retaining real/sim overlap and all proofs', () => {
  const a = usage('g1')
  const simulated = usage('g1', { role: 'simulated_robot', setting: 'simulation', source_url: 'https://arxiv.org/html/2609.00001v2' })
  const result = hardwareFrequency([device('g1')], [work('a', [a, a, simulated]), work('a', [a]), work('legacy-a', [a], { canonical_work_id: 'a' }), work('b', [a])]).models[0]
  assert.equal(result.work_count, 2)
  assert.equal(result.real_work_count, 2)
  assert.equal(result.simulation_work_count, 1)
  assert.equal(result.sources.length, 2)
  assert.equal(result.sources.find(s => s.work_id === 'a').usages.length, 2)
  assert.equal(result.source_count, 3)
})
test('sorts by work frequency, then stable model name and ID; no alphabetical default', () => {
  const devices = [device('z', 'Zulu'), device('a', 'Alpha'), device('b', 'Beta')]
  const rows = [work('1', [usage('z'), usage('a'), usage('b')]), work('2', [usage('z')])]
  assert.deepEqual(hardwareFrequency(devices, rows).models.map(d => d.hardware_id), ['z', 'a', 'b'])
})
test('unresolved series and anonymous hardware do not enter the model ranking', () => {
  const devices = [device('g1'), device('wuji', 'WUJI 20-DoF', 'family_only'), device('unknown', 'Onboard computer', 'unspecified')]
  const result = hardwareFrequency(devices, [work('a', devices.map(d => usage(d.hardware_id)))])
  assert.deepEqual(result.models.map(d => d.hardware_id), ['g1'])
  assert.equal(result.unresolved.length, 2)
  assert.equal(result.unresolved.find(d => d.hardware_id === 'wuji').sources.length, 1)
})
test('every combination filter applies to the matching use, not an unrelated device in the paper', () => {
  const devices = [device('g1'), { ...device('gpu'), category: 'compute_platform' }]
  const rows = [work('a', [usage('g1'), usage('gpu', { category: 'compute_platform', role: 'training_compute', setting: 'unknown' })])]
  assert.equal(hardwareFrequency(devices, rows, { device: 'gpu', role: 'real_robot' }).models.length, 0)
  assert.equal(hardwareFrequency(devices, rows, { category: 'compute_platform', role: 'training_compute', setting: 'unknown', month: '2026-09' }).models[0].work_count, 1)
  assert.equal(hardwareFrequency(devices, rows, { month: '2026-08' }).models.length, 0)
})
test('candidate works, mention-only/unverified uses, missing evidence and unsafe URLs are excluded', () => {
  const d = device('g1')
  const rows = [work('candidate', [usage('g1')], { relevance_status: 'manual_review' }), ...[
    { review_status: 'candidate' }, { role: 'mentioned' }, { statement: '' }, { source_url: 'javascript:alert(1)' }, { source_url: 'http://127.0.0.1/private' }, { source_url: 'https://user:password@example.org/' }, { category: 'motor' },
  ].map((extra, i) => work(String(i), [usage('g1', extra)]))]
  assert.equal(hardwareFrequency([d], rows).models.length, 0)
})
test('baseline/calibration are separate work counts and preserve their statements', () => {
  const result = hardwareFrequency([device('x')], [work('a', [usage('x', { usage_scope: 'baseline' }), usage('x', { usage_scope: 'calibration' })])]).models[0]
  assert.equal(result.work_count, 1)
  assert.equal(result.baseline_work_count, 1)
  assert.equal(result.calibration_work_count, 1)
  assert.equal(result.sources[0].usages.length, 2)
})
test('control execution and physical-model fitting retain their own compute roles', () => {
  const devices = [{ ...device('cpu'), category: 'compute_platform' }]
  const rows = [work('control', [usage('cpu', { category: 'compute_platform', role: 'control_compute', setting: 'real' })]),
    work('fit', [usage('cpu', { category: 'compute_platform', role: 'model_fitting_compute', setting: 'unknown' })])]
  assert.equal(hardwareFrequency(devices, rows).models[0].work_count, 2)
  assert.equal(hardwareFrequency(devices, rows, { role: 'control_compute' }).models[0].work_count, 1)
  assert.equal(hardwareFrequency(devices, rows, { role: 'model_fitting_compute' }).models[0].work_count, 1)
  assert.equal(hardwareFrequency(devices, rows, { role: 'inference_compute' }).models.length, 0)
})
test('equal display names are not sufficient evidence to merge device identities', () => {
  const rows = hardwareFrequency([device('a', 'Hand'), device('b', 'Hand')], [work('1', [usage('a')]), work('2', [usage('b')])]).models
  assert.equal(rows.length, 2)
  assert.deepEqual(rows.map(r => r.work_count), [1, 1])
})
test('an experiment server specification never becomes a specific training or inference count', () => {
  const cpu = { ...device('cpu'), category: 'compute_platform' }
  const uses = [work('server', [usage('cpu', { category: 'compute_platform', role: 'experiment_compute' })])]
  assert.equal(hardwareFrequency([cpu], uses).models[0].work_count, 1)
  for (const role of ['training_compute', 'inference_compute', 'control_compute']) {
    assert.equal(hardwareFrequency([cpu], uses, { role }).models.length, 0)
  }
  assert.equal(hardwareFrequency([device('g1')], [work('invalid', [usage('g1', { role: 'experiment_compute' })])]).models.length, 0)
})
test('year-only and unknown dates do not fabricate month placement', () => {
  assert.equal(hardwareMonth({ first_public_date: '2026-01-01', first_public_date_precision: 'year' }), 'unknown')
  assert.equal(hardwareMonth({ first_public_date: '2026-09', first_public_date_precision: 'month' }), '2026-09')
})

test('hardware source links pin known arXiv versions while preserving the observed record', () => {
  const row = Object.freeze({ source_url: 'https://arxiv.org/html/2305.01648/', source_version: 'v2' })
  assert.equal(hardwareEvidenceUrl(row), 'https://arxiv.org/html/2305.01648v2')
  assert.equal(row.source_url, 'https://arxiv.org/html/2305.01648/')
  assert.equal(hardwareEvidenceUrl({ source_url: 'https://arxiv.org/html/2305.01648v2', source_version: 'v2' }), 'https://arxiv.org/html/2305.01648v2')
  assert.equal(hardwareEvidenceUrl({ source_url: 'https://arxiv.org/html/2305.01648v1', source_version: 'v2' }), '')
  assert.equal(hardwareEvidenceUrl({ source_url: 'https://example.org/project', source_version: 'v2' }), 'https://example.org/project')
  assert.equal(hardwareEvidenceUrl({ source_url: 'http://127.0.0.1/private', source_version: 'v2' }), '')
})

test('Tail keeps one canonical frequency per model and pins its observed legacy source', () => {
  const read = (folder, name) => fs.readFileSync(new URL(`../data/${folder}/${name}.jsonl`, import.meta.url), 'utf8').trim().split('\n').map(JSON.parse)
  const devices = read('equipment', 'devices')
  const byDevice = new Map(devices.map(d => [d.hardware_id, d]))
  const id = 'doi:10.1109/icra57147.2024.10610049'
  const uses = read('equipment', 'usage-evidence').filter(u => u.work_id === id)
  assert.equal(uses.length, 8)
  assert.ok(uses.every(u => u.source_url === 'https://arxiv.org/html/2305.01648' && u.source_version === 'v2'))
  assert.ok(uses.every(u => hardwareEvidenceUrl(u) === 'https://arxiv.org/html/2305.01648v2'))
  const rows = [work(id, uses.map(u => ({ ...u, category: byDevice.get(u.hardware_id).category })), { first_public_date: null, first_public_date_precision: 'unknown' })]
  const models = hardwareFrequency(devices, rows).models
  assert.equal(models.length, 4)
  assert.ok(models.every(m => m.work_count === 1 && m.real_work_count === 1 && m.simulation_work_count === 1))
  assert.equal(hardwareMonth(rows[0]), 'unknown')
  const reading = read('hardware-review', 'fulltext-readings').find(r => r.work_id === id)
  assert.equal(reading.versioned_source_url, 'https://arxiv.org/html/2305.01648v2')
})

test('VLA steering does not invent an exact GPU or arm; GE-PGP separates fitting from query timing', () => {
  const read = name => fs.readFileSync(new URL(`../data/equipment/${name}.jsonl`, import.meta.url), 'utf8').trim().split('\n').map(JSON.parse)
  const devices = new Map(read('devices').map(d => [d.hardware_id, d]))
  const uses = read('usage-evidence')
  const vla = uses.filter(u => u.work_id === 'arxiv:2606.12299')
  assert.equal(vla.length, 4)
  assert.ok(vla.every(u => devices.get(u.hardware_id).identity_level !== 'model_specified'))
  const cpu = uses.filter(u => u.work_id === 'arxiv:2602.12487' && devices.get(u.hardware_id).category === 'compute_platform')
  assert.deepEqual(cpu.map(u => u.role).sort(), ['inference_compute', 'model_fitting_compute'])
  assert.ok(cpu.every(u => devices.get(u.hardware_id).name === 'AMD 5800X'))
})
test('source cards distinguish later review from observation time without claiming a refetch', () => {
  const view = fs.readFileSync(new URL('../docs/.vitepress/theme/components/HardwareFrequencyRow.vue', import.meta.url), 'utf8')
  assert.match(view, /复核 \{\{ eventDate\(usage\.reviewed_at\) \}\}/)
  assert.match(view, /来源记录 \{\{ eventDate\(usage\.observed_at\) \}\}/)
  assert.doesNotMatch(view, /来源获取 \{\{ eventDate\(usage\.observed_at\) \}\}/)
  assert.match(view, /usage\.extends_review_id/)
  assert.match(view, /原记录保留/)
  assert.doesNotMatch(view, /核验 \{\{ eventDate\(usage\.observed_at\) \}\}/)
})

test('source-reviewed hardware conditions remain understandable and do not upgrade unknown vendors', () => {
  const view = fs.readFileSync(new URL('../docs/.vitepress/theme/components/HardwareFrequencyRow.vue', import.meta.url), 'utf8')
  for (const text of ['固定手腕支撑，不代表策略主动控制机械臂', '评测真值网格采集，不是在线感知输入', '仿真吞吐测试，不是机载推理', '如报型号的厂商身份待核', '厂商未明确']) assert.ok(view.includes(text))
  assert.match(view, /vendorLabels\[device\.vendor\]/)
})

test('PM-01 hooks and operator goals remain explicit in hardware source cards', () => {
  const view = fs.readFileSync(new URL('../docs/.vitepress/theme/components/HardwareFrequencyRow.vue', import.meta.url), 'utf8')
  assert.ok(view.includes("real_brachiation_with_goal_and_passive_hooks: '真机横杆移动；操作员指定目标、使用被动挂钩'"))
  assert.ok(view.includes("onboard_lidar_for_sparse_structure_control: '机载激光雷达用于稀疏结构感知控制'"))
  const read = name => fs.readFileSync(new URL(`../data/equipment/${name}.jsonl`, import.meta.url), 'utf8').trim().split('\n').map(JSON.parse)
  const devices = new Map(read('devices').map(d => [d.hardware_id, d]))
  const uses = read('usage-evidence').filter(u => u.work_id === 'arxiv:2608.29769')
  assert.equal(uses.length, 3)
  const real = uses.find(u => u.validation_context === 'real_brachiation_with_goal_and_passive_hooks')
  assert.equal(real.role, 'real_robot')
  assert.equal(devices.get(real.hardware_id).vendor, 'unknown')
  const simulated = uses.find(u => u.role === 'simulated_robot')
  assert.equal(simulated.hardware_id, real.hardware_id)
  const lidar = uses.find(u => u.validation_context === 'onboard_lidar_for_sparse_structure_control')
  assert.equal(lidar.role, 'sensing')
  assert.equal(devices.get(lidar.hardware_id).identity_level, 'model_specified')
})

test('VERA separates simulation and planner training; Koala camera identity and test load cell remain bounded', () => {
  const read = name => fs.readFileSync(new URL(`../data/equipment/${name}.jsonl`, import.meta.url), 'utf8').trim().split('\n').map(JSON.parse)
  const devices = new Map(read('devices').map(d => [d.hardware_id, d]))
  const uses = read('usage-evidence')
  const vera = uses.filter(u => u.work_id === 'arxiv:2605.27817')
  assert.equal(vera.length, 7)
  assert.deepEqual(vera.filter(u => u.hardware_id === 'hardware:franka-panda').map(u => u.role).sort(), ['real_robot', 'simulated_robot'])
  assert.ok(vera.filter(u => devices.get(u.hardware_id).category === 'compute_platform').every(u => u.role === 'training_compute'))
  const koala = uses.filter(u => u.work_id === 'arxiv:2608.20546')
  assert.equal(koala.length, 6)
  assert.ok(koala.some(u => u.hardware_id === 'hardware:franka-research-3'))
  const p200 = koala.find(u => devices.get(u.hardware_id).name.includes('P200'))
  assert.equal(p200.usage_scope, 'baseline')
  assert.match(p200.validation_context, /not_closed_loop_policy_sensor/)
  const camera = koala.find(u => devices.get(u.hardware_id).name.includes('OV9782'))
  assert.equal(devices.get(camera.hardware_id).identity_level, 'family_only')
  const view = fs.readFileSync(new URL('../docs/.vitepress/theme/components/HardwareFrequencyRow.vue', import.meta.url), 'utf8')
  assert.ok(view.includes('仅台架力度对照测量，不是策略反馈或传感器校准'))
})

test('original-paper hardware assertions retain support-only, ground-truth and unknown-model boundaries', () => {
  const read = name => fs.readFileSync(new URL(`../data/equipment/${name}.jsonl`, import.meta.url), 'utf8').trim().split('\n').map(JSON.parse)
  const devices = new Map(read('devices').map(d => [d.hardware_id, d]))
  const uses = read('usage-evidence')
  const pending = uses.find(u => u.work_id === 'arxiv:2609.09941' && u.validation_context === 'real_manipulation_reported_model_identity_pending')
  assert.ok(pending)
  assert.equal(devices.get(pending.hardware_id).identity_level, 'family_only')
  assert.equal(devices.get(pending.hardware_id).vendor, 'unknown')
  assert.notEqual(pending.hardware_id, 'hardware:unitree-g1')
  const mount = uses.find(u => u.work_id === 'arxiv:2609.10137' && u.hardware_id === 'hardware:franka-research-3')
  assert.equal(mount.validation_context, 'fixed_wrist_mount_not_active_arm_policy')
  const scanner = uses.find(u => u.work_id === 'arxiv:2609.08493' && u.hardware_id === 'hardware:einscan-pro-2x-v2')
  assert.equal(scanner.role, 'data_collection')
  assert.equal(scanner.validation_context, 'evaluation_ground_truth_mesh_acquisition')
  const throughput = uses.find(u => u.work_id === 'arxiv:2609.12677' && u.hardware_id === 'hardware:nvidia-rtx-4090')
  assert.equal(throughput.role, 'experiment_compute')
  assert.equal(throughput.validation_context, 'simulation_throughput_benchmark')
  assert.equal(uses.find(u => u.work_id === 'arxiv:2609.09630' && u.hardware_id === 'hardware:nvidia-rtx-3090').role, 'inference_compute')
})
test('cRVAE keeps robot models and mocap phases separate without turning a GPU donation into usage', () => {
  const read = name => fs.readFileSync(new URL(`../data/equipment/${name}.jsonl`, import.meta.url), 'utf8').trim().split('\n').map(JSON.parse)
  const devices = read('devices')
  const byDevice = new Map(devices.map(d => [d.hardware_id, d]))
  const uses = read('usage-evidence').filter(u => u.work_id === 'arxiv:2609.10308')
  assert.equal(uses.length, 5)
  for (const id of ['hardware:unitree-go2', 'hardware:unitree-d1', 'hardware:so-101']) {
    const row = uses.find(u => u.hardware_id === id)
    assert.ok(row)
    assert.equal(row.role, 'real_robot')
    assert.equal(row.setting, 'real')
    assert.equal(byDevice.get(id).identity_level, 'model_specified')
  }
  assert.equal(uses.filter(u => byDevice.get(u.hardware_id).category === 'compute_platform').length, 0)
  const mocap = uses.filter(u => byDevice.get(u.hardware_id).identity_level === 'unspecified')
  assert.equal(mocap.length, 2)
  assert.equal(new Set(mocap.map(u => u.hardware_id)).size, 1)
  assert.deepEqual(mocap.map(u => `${u.role}:${u.usage_scope}`).sort(), ['data_collection:calibration', 'sensing:study'])
  const rows = [work('arxiv:2609.10308', uses.map(u => ({ ...u, category: byDevice.get(u.hardware_id).category })))]
  const result = hardwareFrequency(devices, rows)
  assert.equal(result.models.length, 3)
  assert.equal(result.unresolved.length, 1)
  assert.equal(result.unresolved[0].work_count, 1)
  assert.equal(result.unresolved[0].sources[0].usages.length, 2)
})
test('MuJoCable reading retains actual article coverage, version and hardware validation limits', () => {
  const readings = fs.readFileSync(new URL('../data/hardware-review/fulltext-readings.jsonl', import.meta.url), 'utf8').trim().split('\n').map(JSON.parse)
  const row = readings.find(r => r.work_id === 'arxiv:2609.09612' && r.version === 'v2')
  assert.ok(row)
  assert.equal(row.article_chars, 37509)
  assert.deepEqual(row.read_ranges, [{ start: 0, end: 20000 }, { start: 20000, end: 37509 }])
  assert.deepEqual(row.checked_table_ids, ['S2.T1', 'S4.T2', 'S4.T3'])
  assert.equal(row.images_inspected, false)
  assert.equal(row.supplementary_materials_inspected, false)
  assert.ok(row.limitations_zh.some(r => r.text_zh.includes('不是整只Faive手的真机使用')))
  assert.ok(row.limitations_zh.some(r => r.text_zh.includes('没有训练或验证强化学习控制策略')))
})
test('PccDiffuser benchmark hardware does not become training, onboard compute or an invented robot model', () => {
  const read = name => fs.readFileSync(new URL(`../data/equipment/${name}.jsonl`, import.meta.url), 'utf8').trim().split('\n').map(JSON.parse)
  const devices = new Map(read('devices').map(d => [d.hardware_id, d]))
  const uses = read('usage-evidence').filter(u => u.work_id === 'arxiv:2609.09745')
  assert.equal(uses.length, 3)
  const compute = uses.filter(u => devices.get(u.hardware_id).category === 'compute_platform')
  assert.deepEqual(compute.map(u => devices.get(u.hardware_id).name).sort(), ['AMD EPYC 9224', 'NVIDIA RTX 5090'])
  assert.ok(compute.every(u => u.role === 'experiment_compute' && u.validation_context === 'planning_computation_benchmark'))
  const robot = uses.find(u => devices.get(u.hardware_id).category === 'robot_arm')
  assert.equal(devices.get(robot.hardware_id).identity_level, 'unspecified')
  assert.equal(robot.validation_context, 'planned_trajectory_execution_feedback_not_established')
  assert.match(robot.statement, /不是此原型的真实试验成功率/)
})
test('ObstaDiff preserves learned-approach/replay stages and separate deployment/training GPUs', () => {
  const read = name => fs.readFileSync(new URL(`../data/equipment/${name}.jsonl`, import.meta.url), 'utf8').trim().split('\n').map(JSON.parse)
  const devices = new Map(read('devices').map(d => [d.hardware_id, d]))
  const uses = read('usage-evidence').filter(u => u.work_id === 'arxiv:2609.10918')
  assert.equal(uses.length, 5)
  const sawyer = uses.filter(u => devices.get(u.hardware_id).name === 'Rethink Robotics Sawyer')
  assert.deepEqual(sawyer.map(u => u.role).sort(), ['data_collection', 'real_robot'])
  assert.equal(sawyer.find(u => u.role === 'real_robot').validation_context, 'learned_alignment_then_demonstration_replay')
  const card = name => uses.find(u => devices.get(u.hardware_id).name === name)
  assert.equal(card('NVIDIA GeForce RTX 2080 Ti').role, 'inference_compute')
  assert.equal(card('NVIDIA RTX 6000 Ada').role, 'training_compute')
  assert.equal(card('Intel RealSense D455').validation_context, 'eye_in_hand_alignment_visual_input')
})
test('DIA wall-clock training GPU is not a real robot or inference-latency measurement', () => {
  const uses = fs.readFileSync(new URL('../data/equipment/usage-evidence.jsonl', import.meta.url), 'utf8').trim().split('\n').map(JSON.parse).filter(u => u.work_id === 'arxiv:2609.12245')
  assert.equal(uses.length, 1)
  assert.equal(uses[0].hardware_id, 'hardware:nvidia-rtx-3090')
  assert.equal(uses[0].role, 'training_compute')
  assert.equal(uses[0].validation_context, 'simulation_policy_training')
  assert.match(uses[0].statement, /不是策略单次推理延迟/)
})
test('TFGCA retains unspecified variants, memory configuration and simulation-only ALOHA', () => {
  const read = name => fs.readFileSync(new URL(`../data/equipment/${name}.jsonl`, import.meta.url), 'utf8').trim().split('\n').map(JSON.parse)
  const devices = new Map(read('devices').map(d => [d.hardware_id, d]))
  const uses = read('usage-evidence').filter(u => u.work_id === 'arxiv:2609.09925')
  assert.equal(uses.length, 3)
  assert.ok(uses.every(u => devices.get(u.hardware_id).identity_level === 'family_only'))
  const a2 = uses.find(u => u.role === 'real_robot')
  assert.notEqual(a2.hardware_id, 'hardware:agibot-expedition-a2')
  assert.match(a2.configuration, /37\/60/)
  const gpu = uses.find(u => u.role === 'training_compute')
  assert.match(gpu.configuration, /80GB/)
  const aloha = uses.find(u => u.role === 'simulated_robot')
  assert.equal(aloha.setting, 'simulation')
  assert.match(aloha.statement, /不是实体ALOHA部署/)
})
test('GHOST ties original HTML to its DOI work and separates user control, sensors and unknown GPU', () => {
  const read = name => fs.readFileSync(new URL(`../data/equipment/${name}.jsonl`, import.meta.url), 'utf8').trim().split('\n').map(JSON.parse)
  const devices = new Map(read('devices').map(d => [d.hardware_id, d]))
  const uses = read('usage-evidence').filter(u => u.work_id === 'doi:10.1109/lra.2026.3726328')
  assert.equal(uses.length, 7)
  assert.ok(uses.every(u => u.source_url === 'https://arxiv.org/html/2608.29080v1'))
  assert.equal(uses.find(u => devices.get(u.hardware_id).name === 'Boston Dynamics Spot').validation_context, 'human_operated_dual_robot_teleoperation')
  assert.equal(uses.find(u => u.usage_scope === 'baseline').role, 'data_collection')
  const gpu = uses.find(u => u.role === 'inference_compute')
  assert.equal(devices.get(gpu.hardware_id).identity_level, 'unspecified')
  assert.match(gpu.statement, /71fps是头显渲染/)
  assert.equal(read('usage-evidence').filter(u => u.work_id === 'arxiv:2608.29080').length, 0)
})
test('DART sensor additions do not duplicate its robot or make Fitbit a feedback controller', () => {
  const read = name => fs.readFileSync(new URL(`../data/equipment/${name}.jsonl`, import.meta.url), 'utf8').trim().split('\n').map(JSON.parse)
  const devices = new Map(read('devices').map(d => [d.hardware_id, d]))
  const uses = read('usage-evidence').filter(u => u.work_id === 'arxiv:2609.12349')
  assert.equal(uses.length, 6)
  assert.equal(uses.filter(u => u.hardware_id === 'hardware:blossom').length, 1)
  assert.equal(uses.filter(u => u.hardware_id === 'hardware:raspberry-pi-family-7b67c553a1').length, 1)
  const fitbit = uses.find(u => devices.get(u.hardware_id).vendor === 'Fitbit')
  assert.equal(fitbit.role, 'data_collection')
  assert.equal(devices.get(fitbit.hardware_id).identity_level, 'family_only')
  assert.equal(fitbit.validation_context, 'physiology_recording_not_real_time_robot_adaptation')
  assert.ok(uses.some(u => u.validation_context === 'audiovisual_research_recording_not_speech_input'))
})
test('DARP keeps exact arm model and unspecified camera identity, with separate calibration use', () => {
  const read = name => fs.readFileSync(new URL(`../data/equipment/${name}.jsonl`, import.meta.url), 'utf8').trim().split('\n').map(JSON.parse)
  const devices = new Map(read('devices').map(d => [d.hardware_id, d]))
  const uses = read('usage-evidence').filter(u => u.work_id === 'arxiv:2608.31002')
  assert.equal(uses.length, 3)
  const arm = uses.find(u => devices.get(u.hardware_id).name === 'Unitree Z1 Pro')
  assert.equal(arm.role, 'data_collection')
  assert.equal(devices.get(arm.hardware_id).identity_level, 'model_specified')
  assert.equal(arm.validation_context, 'alternating_dual_arm_multiview_data_acquisition')
  const cameras = uses.filter(u => devices.get(u.hardware_id).category === 'vision_sensor')
  assert.equal(new Set(cameras.map(u => u.hardware_id)).size, 1)
  assert.ok(cameras.every(u => devices.get(u.hardware_id).identity_level === 'family_only'))
  assert.deepEqual(cameras.map(u => u.usage_scope).sort(), ['calibration', 'study'])
})
test('AcrossVAM dataset robot names do not create verified physical hardware usage', () => {
  const read = path => fs.readFileSync(new URL(path, import.meta.url), 'utf8').trim().split('\n').map(JSON.parse)
  const id = 'arxiv:2608.28491'
  assert.equal(read('../data/equipment/usage-evidence.jsonl').filter(u => u.work_id === id).length, 0)
  const review = read('../data/hardware-review/section-reviews.jsonl').find(r => r.work_id === id)
  assert.equal(review.decision, 'ambiguous')
  assert.equal(review.whole_paper_hardware_absence_conclusion, false)
  assert.equal(review.assertion_count, 0)
  const reading = read('../data/hardware-review/fulltext-readings.jsonl').find(r => r.work_id === id)
  assert.ok(reading.limitations_zh.some(r => r.text_zh.includes('闭环控制列为未来')))
})
test('Blind Dexterity separates qualitative real transfer from quantitative simulation', () => {
  const uses = fs.readFileSync(new URL('../data/equipment/usage-evidence.jsonl', import.meta.url), 'utf8').trim().split('\n').map(JSON.parse).filter(u => u.work_id === 'arxiv:2608.29487')
  assert.equal(uses.length, 2)
  assert.ok(uses.every(u => u.hardware_id === 'hardware:unitree-g1'))
  const real = uses.find(u => u.setting === 'real')
  assert.equal(real.validation_context, 'real_robot_qualitative_transfer_only')
  assert.match(real.configuration, /机载IMU/)
  assert.match(real.statement, /表格成功率全部来自仿真/)
  assert.equal(uses.find(u => u.setting === 'simulation').validation_context, 'simulation_quantitative_policy_evaluation')
})
test('frozen audited authority cohort: G1 16 works, PiPER-X one real work, WUJI one simulation-only family', () => {
  // Use tracked authority rather than ignored/generated API so clean CI works.
  const read = name => fs.readFileSync(new URL(`../data/equipment/${name}.jsonl`, import.meta.url), 'utf8').trim().split('\n').map(JSON.parse)
  const devices = read('devices')
  const byDevice = new Map(devices.map(d => [d.hardware_id, d]))
  const cohort = new Set(['arxiv:2509.20322', 'arxiv:2510.02252', 'arxiv:2510.03022', 'arxiv:2510.05070', 'arxiv:2511.02832', 'arxiv:2511.15200', 'arxiv:2602.06643', 'arxiv:2602.10106', 'arxiv:2602.16710', 'arxiv:2603.12263', 'arxiv:2606.22174', 'arxiv:2606.23680', 'arxiv:2608.06375', 'arxiv:2608.17027', 'arxiv:2609.05994', 'arxiv:2609.06591', 'arxiv:2609.12081'])
  const byWork = new Map()
  for (const row of read('usage-evidence')) { if (!cohort.has(row.work_id)) continue; const list = byWork.get(row.work_id) || []; list.push({ ...row, category: byDevice.get(row.hardware_id)?.category }); byWork.set(row.work_id, list) }
  const rows = [...byWork].map(([id, uses]) => work(id, uses))
  const result = hardwareFrequency(devices, rows)
  const g1 = result.models.find(d => d.hardware_id === 'hardware:unitree-g1')
  assert.equal(g1.work_count, 16)
  assert.equal(g1.real_work_count, 14)
  assert.equal(g1.simulation_work_count, 8)
  assert.equal(result.models.find(d => d.hardware_id === 'hardware:agilex-piper-x').real_work_count, 1)
  const wuji = result.unresolved.find(d => /WUJI/.test(d.name))
  assert.equal(wuji.work_count, 1)
  assert.equal(wuji.real_work_count, 0)
  assert.equal(wuji.simulation_work_count, 1)
})
