#!/usr/bin/env python3
"""Explicit lossless source-records migration; default is a read-only dry-run.

--apply requires fresh absolute --stage-dir and --backup-dir outside catalog,
on the same filesystem. It stages all 256 partitions, verifies every ID,
complete JSON value and original line bytes, then archives the legacy file
and installs the completed directory. manifest.json is never rewritten.

Run with quiescent writers. A marker makes readers/writers fail closed during
the two renames. Ordinary failures are rolled back if generated bytes remain
unchanged. This is NOT an atomic/power-loss-safe multi-file transaction: after
abrupt termination, keep the marker, stage and backup for explicit recovery.
Never delete a recovery marker before inspecting its exact paths and hashes.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import os
import sys
from pathlib import Path

sys.dont_write_bytecode = True

from source_record_store import (
    ID, LEGACY, TABLE, MIGRATION_MARKER, SHARD_NAMES, canonical, digest,
    parse_lines, partition_paths, read_bytes, shard_name, source_record_layout,
    strict_json, validated_rows,
)

ROOT = Path(__file__).resolve().parents[1]


def fail(code):
    raise ValueError("source_record_migration:" + code)


def sha(raw):
    return hashlib.sha256(raw).hexdigest()


def safe_directory(path):
    path = Path(path)
    if not path.is_absolute() or ".." in path.parts:
        fail("absolute_normalized_directory_required")
    for parent in (path, *path.parents):
        if parent.is_symlink():
            fail("symlink_directory_not_allowed")
    if not path.is_dir():
        fail("directory_missing")
    return path


def table_hash(rows):
    """Exactly catalog_store.fingerprint(sorted(rows, key=encode))."""
    result = hashlib.sha256(b"[")
    for index, text in enumerate(sorted(canonical(row) for row in rows)):
        if index:
            result.update(b",")
        result.update(text.encode("utf-8"))
    result.update(b"]")
    return result.hexdigest()


def entries_from_directory(directory):
    entries = []
    for path in partition_paths(directory):
        entries.extend(parse_lines(read_bytes(path), expected_shard=path.name, strict_lines=True))
    validated_rows([row for row, _ in entries])
    return {row[ID]: (row, line) for row, line in entries}


def compare_entries(before, after):
    if set(before) != set(after):
        fail("source_id_set_changed")
    for source_id, (row, line) in before.items():
        actual_row, actual_line = after[source_id]
        if canonical(row) != canonical(actual_row):
            fail("source_fields_changed")
        if line != actual_line:
            fail("source_original_line_bytes_changed")


def snapshot(catalog):
    layout = source_record_layout(catalog)
    if layout == "missing":
        fail("source_table_missing")
    manifest_raw = read_bytes(catalog / "manifest.json")
    manifest = strict_json(manifest_raw.decode("utf-8"))
    legacy_raw = None
    if layout == "legacy":
        legacy_raw = read_bytes(catalog / LEGACY)
        entries = parse_lines(legacy_raw, strict_lines=True)
        rows = validated_rows([row for row, _ in entries])
        if [row[ID] for row, _ in entries] != [row[ID] for row in rows]:
            fail("legacy_id_order_requires_review")
        by_id = {row[ID]: (row, line) for row, line in entries}
    else:
        by_id = entries_from_directory(catalog / TABLE)
        rows = [by_id[key][0] for key in sorted(by_id)]
    logical_hash = table_hash(rows)
    hashes = manifest.get("table_hashes")
    if not isinstance(hashes, dict) or hashes.get(TABLE) != logical_hash:
        fail("manifest_source_table_hash_mismatch")
    if manifest.get("catalog_hash") != digest(hashes):
        fail("manifest_catalog_hash_mismatch")
    partitions = {name: [] for name in SHARD_NAMES}
    original_lines = hashlib.sha256()
    for source_id in sorted(by_id):
        _, line = by_id[source_id]
        partitions[shard_name(source_id)].append(line)
        original_lines.update((canonical([source_id, sha(line)]) + "\n").encode("utf-8"))
    shard_info = {}
    for name, lines in partitions.items():
        content_hash = hashlib.sha256()
        for line in lines:
            content_hash.update(line)
        shard_info[name] = {"count": len(lines), "bytes": sum(map(len, lines)), "sha256": content_hash.hexdigest()}
    report = {"schema_version": "1", "status": "ready" if layout == "legacy" else "already_sharded",
              "applied": False, "layout_before": layout, "source_record_count": len(rows),
              "partition_algorithm": "sha1(source_record_id UTF-8)[:2]", "shard_count": 256,
              "source_table_hash": logical_hash, "catalog_hash": manifest["catalog_hash"],
              "ingested_at": manifest.get("ingested_at"), "manifest_sha256": sha(manifest_raw),
              "legacy_sha256": sha(legacy_raw) if legacy_raw is not None else None,
              "original_line_bytes_digest": original_lines.hexdigest(),
              "line_digest_method": "sha256 of ID-sorted canonical [source_record_id,sha256(original_line_bytes)] plus LF",
              "shards": shard_info, "cross_file_power_loss_atomic": False}
    return {"by_id": by_id, "partitions": partitions, "manifest_raw": manifest_raw,
            "legacy_raw": legacy_raw, "report": report}


def fresh_output(path, catalog):
    if path is None:
        fail("apply_requires_stage_and_backup_directories")
    path = Path(path)
    if not path.is_absolute() or ".." in path.parts:
        fail("absolute_normalized_output_required")
    safe_directory(path.parent)
    if os.path.lexists(path):
        fail("output_directory_already_exists")
    if path == catalog or catalog in path.parents or path in catalog.parents:
        fail("output_overlaps_catalog")
    if path.parent.stat().st_dev != catalog.stat().st_dev:
        fail("output_must_share_catalog_filesystem")
    return path


def exclusive_write(path, raw):
    with path.open("xb") as stream:
        stream.write(raw)
        stream.flush()
        os.fsync(stream.fileno())


def assert_legacy_unchanged(catalog, before):
    if source_record_layout(catalog) != "legacy":
        fail("source_layout_changed_before_switch")
    if read_bytes(catalog / LEGACY) != before["legacy_raw"]:
        fail("source_changed_before_switch")
    if read_bytes(catalog / "manifest.json") != before["manifest_raw"]:
        fail("manifest_changed_before_switch")


def remove_owned_marker(marker, raw):
    if read_bytes(marker) != raw:
        fail("migration_marker_changed")
    marker.unlink()


def rollback(catalog, stage_data, backup, before, marker_raw):
    """Only restore our exact verified outputs; never overwrite other edits."""
    marker = catalog / MIGRATION_MARKER
    if read_bytes(marker) != marker_raw or read_bytes(catalog / "manifest.json") != before["manifest_raw"]:
        fail("rollback_concurrent_edit_recovery_required")
    if (catalog / TABLE).exists():
        compare_entries(before["by_id"], entries_from_directory(catalog / TABLE))
        if os.path.lexists(stage_data):
            fail("rollback_stage_destination_changed")
        os.rename(catalog / TABLE, stage_data)
    legacy, archived = catalog / LEGACY, backup / LEGACY
    if os.path.lexists(legacy):
        if read_bytes(legacy) != before["legacy_raw"]:
            fail("rollback_legacy_changed")
    else:
        if read_bytes(archived) != before["legacy_raw"]:
            fail("rollback_backup_changed")
        # Copy, not move, so the recovery archive stays available after failure.
        temporary = backup / "rollback-source-records.tmp"
        exclusive_write(temporary, before["legacy_raw"])
        if os.path.lexists(legacy):
            fail("rollback_legacy_reappeared")
        os.rename(temporary, legacy)
    remove_owned_marker(marker, marker_raw)


def migrate(catalog, *, stage_dir=None, backup_dir=None, apply=False):
    catalog = safe_directory(catalog)
    before = snapshot(catalog)
    report = before["report"]
    if not apply or report["status"] == "already_sharded":
        return report
    stage, backup = fresh_output(stage_dir, catalog), fresh_output(backup_dir, catalog)
    if stage == backup or stage in backup.parents or backup in stage.parents:
        fail("stage_and_backup_overlap")
    stage.mkdir(mode=0o700)
    stage_data = stage / TABLE
    stage_data.mkdir(mode=0o700)
    for name in SHARD_NAMES:
        with (stage_data / name).open("xb") as stream:
            for line in before["partitions"][name]:
                stream.write(line)
            stream.flush()
            os.fsync(stream.fileno())
    compare_entries(before["by_id"], entries_from_directory(stage_data))
    exclusive_write(stage / "migration-plan.json", (canonical(report) + "\n").encode("utf-8"))
    assert_legacy_unchanged(catalog, before)
    backup.mkdir(mode=0o700)
    exclusive_write(backup / "manifest.json", before["manifest_raw"])
    marker = catalog / MIGRATION_MARKER
    marker_raw = (canonical({"schema_version": "1", "stage_directory": str(stage), "backup_directory": str(backup),
                            "legacy_sha256": report["legacy_sha256"], "manifest_sha256": report["manifest_sha256"],
                            "source_table_hash": report["source_table_hash"],
                            "recovery_note": "Explicit recovery required after interruption; do not delete marker blindly."}) + "\n").encode("utf-8")
    exclusive_write(marker, marker_raw)
    try:
        # Our marker now blocks normal source readers and save_catalog writers.
        # Compare bytes again without bypassing any existing foreign marker.
        if read_bytes(catalog / LEGACY) != before["legacy_raw"] or read_bytes(catalog / "manifest.json") != before["manifest_raw"]:
            fail("source_or_manifest_changed_at_switch")
        if os.path.lexists(catalog / TABLE) or os.path.lexists(backup / LEGACY):
            fail("migration_destination_reappeared")
        os.rename(catalog / LEGACY, backup / LEGACY)
        os.rename(stage_data, catalog / TABLE)
        compare_entries(before["by_id"], entries_from_directory(catalog / TABLE))
        if read_bytes(backup / LEGACY) != before["legacy_raw"] or read_bytes(catalog / "manifest.json") != before["manifest_raw"]:
            fail("source_or_manifest_changed_after_switch")
        remove_owned_marker(marker, marker_raw)
    except Exception as error:
        try:
            rollback(catalog, stage_data, backup, before, marker_raw)
        except Exception as recovery_error:
            raise RuntimeError("source_record_migration:rollback_failed_explicit_recovery_required; "
                               "retain marker, stage and backup") from recovery_error
        raise RuntimeError("source_record_migration:switch_failed_legacy_restored; retain stage and backup") from error
    result = {**report, "status": "migrated", "applied": True, "stage_directory": str(stage), "backup_directory": str(backup)}
    # This report is outside the authority. Failure to persist it does not
    # invalidate the verified table or silently undo an already completed swap.
    try:
        exclusive_write(backup / "migration-receipt.json", (canonical(result) + "\n").encode("utf-8"))
    except OSError:
        result["receipt_warning"] = "archive_receipt_write_failed; source and manifest already verified"
    return result


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--catalog", type=Path, default=ROOT / "data/catalog")
    parser.add_argument("--stage-dir", type=Path)
    parser.add_argument("--backup-dir", type=Path)
    parser.add_argument("--apply", action="store_true")
    args = parser.parse_args(argv)
    try:
        result = migrate(args.catalog, stage_dir=args.stage_dir, backup_dir=args.backup_dir, apply=args.apply)
        print(canonical(result))
        return 0
    except (ValueError, RuntimeError, OSError, UnicodeError) as error:
        # Fixed codes only; never emit row contents or source payloads.
        message = str(error) if str(error).startswith(("source_record_store:", "source_record_migration:")) else "source_record_migration:io_or_json_validation_failed"
        parser.exit(2, message + "\n")


if __name__ == "__main__":
    raise SystemExit(main())
